### ISSUE TITLE
"One to many" utilisation filtre sur liste standard

### ISSUE THREAD

**Issue by LaraSpeed** [LaraSpeed/LaraSpeed#1]
# Voir mail de BB du  ven. 18/11/2016 13:46

### Mail copy without images:
Seydou,

En prenant comme exemple la navigation de la liste des langages vers les films dans le langage sélectionné :

Le choix d’une langue enchaine sur la liste des films de la langue en affichant la liste des films avec un filtre sur la langue. La langue courante est mise par défaut au moment de l’ajout d’un nouveau film ; l’utilisateur a la possibilité de changer la langue s’il veut créer un film dans une autre langue.

Quand l’utilisateur veut voir les film quelle que soit la langue, il doit utiliser le choix film du menu vertical.

N’hésites pas à me demander des éclaircissements si ce n’est pas limpide.

A te lire,
bien cordialement.
Bernard BALLESTA
Mobile: 06 88 43 94 32

**Comment by ArianeFire** [comment]
Fait, il me reste le referencement du language lors de la creaion du film.
Teste : [http://163.172.174.219/LaraSpeed/public/film/](url).

**Comment by ArianeFire** [comment]
Bernard, 
Le referencement du langue lors de la creation de film a été fait.
Teste : [http://163.172.174.219/LaraSpeed/public/film](url).
