### ISSUE TITLE
Limiter les colonnes à afficher dans la liste

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#10]
Limiter les colonnes à afficher dans la liste pour que tout tienne dans l’écran.
 
Limiter au niveau du MCD :
      ·        Aucune colonne spécifiée :
            o   Inclure toutes les colonnes
     ·        Colonnes spécifiés
            o   Inclure les colonnes spécifiées seulement

![image001 1](https://cloud.githubusercontent.com/assets/12550052/22854236/d55e5bea-f061-11e6-8938-bfde66085d32.jpg)

**Comment by ArianeFire** [comment]
Ce point a été gérer en allant du principe que tout element non obligatoire (required) ne sera pas visible dans la liste, Tu peux tester ici : [http://163.172.174.219/LaraSpeedV2/public/film](url)
Que t'en semble ?

**Comment by ballesta** [comment]
Je penses que c’est une possibilité qu’il faut utiliser quand le nombre de colonnes à afficher est important :  >7 par exemple.

 

Mais nous devons donner la possibilité d’inclure ou d’exclure individuellement des colonnes de la liste afin de pouvoir adapter les listes aux besoins clients ;

 

De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : lundi 13 février 2017 23:49
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Limiter les colonnes à afficher dans la liste (#10)

 

Ce point a été gérer en allant du principe que tout element non obligatoire (required) ne sera pas visible dans la liste, Tu peux tester ici : http://163.172.174.219/LaraSpeedV2/public/film
Que t'en semble ?

**Comment by ArianeFire** [comment]
Effectivement, je vais tenir compte de ça dans l'implementation !

**Comment by ArianeFire** [comment]
C'est bon maintenant comme sur l'image, on peut specifier pour chaque attributs si c'est à afficher ou non à l'aide d'un paramètre  (Voir image) : 

![mcdn](https://cloud.githubusercontent.com/assets/12550052/22946391/2d057704-f2ef-11e6-89a9-0c7e364273b8.png)

Tester : [http://163.172.174.219/LaraSpeedV2/public/film](url)
