### ISSUE TITLE
Même présentation pour les fiches Ajout visualisation, modification

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#12]
La présentation pour la modification me semble une bonne base pour les autre fiches.
Je penses que Laravel permet de ne développer qu’un seul source pour la structure de la fiche qui peut être inclus dans les 3 fiche (+, modif , -).
De mémoire, j’ai vu des info sur le web sur la façon de faire.

![image001 7](https://cloud.githubusercontent.com/assets/12550052/22854272/7bf73c9c-f062-11e6-9ccb-db738c2aca56.png)

**Comment by ArianeFire** [comment]
Jette un coup d'oeil pour voir maintenant : [http://163.172.174.219/LaraSpeedV2/public/film/create?](url)

**Comment by ballesta** [comment]
De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : samedi 11 février 2017 19:51
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Même présentation pour les fiches Ajout visualisation, modification (#12)

 

Jette un coup d'oeil pour voir maintenant : http://163.172.174.219/LaraSpeedV2/public/film/create?

**Comment by ballesta** [comment]
Seydou,

L'application se plante sur impossibilité d'accéder à la base de données.

Bon dimanche,

Bernard


Bernard BALLESTA

**Comment by ArianeFire** [comment]
Voici, c'est un problème lié au fichier .env, c'est bon maintenant : [http://163.172.174.219/LaraSpeedV2/public/film](url)
