### ISSUE TITLE
Présentation des listes

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#13]
![image001 8](https://cloud.githubusercontent.com/assets/12550052/22857666/3fb26164-f0a1-11e6-8c3d-a53479afd74a.png)

**Comment by ballesta** [comment]
Coquille :

 



 

De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : samedi 11 février 2017 22:30
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : [LaraSpeed/LaraSpeed] Présentation des listes (#13)

 

 <https://cloud.githubusercontent.com/assets/12550052/22857666/3fb26164-f0a1-11e6-8c3d-a53479afd74a.png> image001 8

**Comment by ArianeFire** [comment]
Coquille ?
