### ISSUE TITLE
Liaison n-n / éléments sélectionnés réproposés

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#17]
![image001 1](https://cloud.githubusercontent.com/assets/12550052/22865179/76b8e948-f156-11e6-8fda-3cb3540ebe6c.jpg)

**Comment by ArianeFire** [comment]
Ce problème est réglé, tu peux le tester : [http://163.172.174.219/LaraSpeedV2/public/film](url)

**Comment by ballesta** [comment]
De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : lundi 13 février 2017 22:38
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Liaison n-n / éléments sélectionnés réproposés (#17)

 

Ce problème est réglé, tu peux le tester : http://163.172.174.219/LaraSpeedV2/public/film
