### ISSUE TITLE
Modification en mode affichage

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#19]
![image003 1](https://cloud.githubusercontent.com/assets/12550052/22865202/0bea7586-f157-11e6-92e4-7c65d856f19e.jpg)

**Comment by ArianeFire** [comment]
Ce problème a été fixer, tu peux y jeter un coup d'oeil : [http://163.172.174.219/LaraSpeedV2/public/category/3](url)

**Comment by ballesta** [comment]
De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : lundi 13 février 2017 23:05
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Modification en mode affichage (#19)

 

Cette problème a été fixer, tu peux y jeter un coup d'oeil : http://163.172.174.219/LaraSpeedV2/public/category/3
