### ISSUE TITLE
Many to many/Dual list dans formulaire

### ISSUE THREAD

**Issue by ArianeExtern** [LaraSpeed/LaraSpeed#2]
Voir mail de BB

**Comment by ArianeExtern** [comment]
A compléter avec la référence du mail de BB

**Comment by ArianeFire** [comment]
Fait ! 
En guise teste :
Film : [http://163.172.174.219/LaraSpeed/public/film/create](url)
Category : [http://163.172.174.219/LaraSpeed/public/category/create](url)
