### ISSUE TITLE
Problème sur création 'inventory'

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#21]
![image001](https://cloud.githubusercontent.com/assets/12550052/23096389/84db819a-f613-11e6-824f-d9fa67d878b5.png)

![image002](https://cloud.githubusercontent.com/assets/12550052/23096390/85904ab2-f613-11e6-9755-5d915d0bcdaf.png)

**Comment by ArianeFire** [comment]
Bernard, il me semble que ceci est dû au fait que les tables de la base "sakila" ne dispose pas de colonne "created_at" & "updated_at" par défaut contrairement à Laravel qui considère implicitment l'existence de ces champs lors de l'insertion, j'avais ajouté ces champs pour les tables qu'on utiliser au debut du projet.

**Comment by ballesta** [comment]
Je penses que nous devons ajouter les champs created_at et autres utilisés par laravel.

 

De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : samedi 18 février 2017 22:26
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Problème sur création 'inventory' (#21)

 

Bernard, il me semble que ceci est dû au fait que les tables de la base "sakila" ne dispose pas de colonne "created_at" & "updated_at" par défaut contrairement à Laravel qui considère implicitment l'existence de ces champs lors de l'insertion, j'avais ajouté ces champs pour les tables qu'on utiliser au debut du projet.
