### ISSUE TITLE
Ajout client / inventotys

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#23]
![image001 2](https://cloud.githubusercontent.com/assets/12550052/23096416/f9f2c1aa-f613-11e6-8f29-3631850cd777.png)

**Comment by ArianeFire** [comment]
Ce problème vient de la table "inventory", voir image ci-dessous pour les colonnes : 

![inv](https://cloud.githubusercontent.com/assets/12550052/23097020/4d691f0c-f621-11e6-8275-9b0ec96d24f2.png)

Il n'y'a pas d'identifiant parlant comme tu peux le voir, qu'est ce que tu proposes ? je me disais que j'ai surement raté quelque chose sur la l'interpretation du schema.

**Comment by ballesta** [comment]
D’accord, mais quand tu navigue d’un film vers les inventories (en fait les CDROM) tu peux afficher le nom du magasin par « store_id ».

 

Ce qui permet de savoir ou il y le film disponible à la location.

 

La méthode générale :

·        Ne pas afficher le parent (film dans notre cas)

·        Afficher les autres champs avec l’identifiant parlant comme dans les listes déroulantes

 

 

De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : samedi 18 février 2017 22:30
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Ajout client / inventotys (#23)

 

Ce problème vient de la table "inventory", voir image ci-dessous pour les colonnes :

 <https://cloud.githubusercontent.com/assets/12550052/23097020/4d691f0c-f621-11e6-8275-9b0ec96d24f2.png> inv

Il n'y'a pas d'identifiant parlant comme tu peux le voir, qu'est ce que tu proposes ?

**Comment by ArianeFire** [comment]
La relation "inventory belongTo store" & "store belongTo adress" a permis de relier inventory à adress, ainsi il a été possible de presenter l'adresse de du store où l'inventory.

Teste : [http://163.172.174.219/LaraSpeedV2/public/customer/create?](url)
