### ISSUE TITLE
Lien au pluriel + explications

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#31]
![image001 1](https://cloud.githubusercontent.com/assets/12550052/23274628/59293bf0-f9fb-11e6-94bf-79e33bdb3466.jpg)

**Comment by ArianeFire** [comment]
Comme tu l'as dit j'ai ajouté la possibilité d'ajouter une explication dans le MCD comme sur l'image ci : 

![explain](https://cloud.githubusercontent.com/assets/12550052/23278254/be6f3d5e-fa08-11e6-9a0b-d034f5b83824.png)

Ici on spécifie que "Le lien représente la liste des Categories associées au Film" etc...

En Guise de teste : [http://163.172.174.219/LaraSpeedV2/public/store/related/2?tab=customer](http://163.172.174.219/LaraSpeedV2/public/store/related/2?tab=customer)

**Comment by ballesta** [comment]
Super, le lien fonctionne !

 

De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : jeudi 23 février 2017 21:48
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Lien au pluriel + explications (#31)

 

Comme tu l'as dit j'ai ajouté la possibilité d'ajouter une explication dans le MCD comme sur l'image ci :

 <https://cloud.githubusercontent.com/assets/12550052/23278254/be6f3d5e-fa08-11e6-9a0b-d034f5b83824.png> explain

Ici on spécifie que "Le lien représente la liste des Categories associées au Film" etc...

En Guise de teste : http://163.172.174.219/LaraSpeedV2/public/store/related/2?tab=customer
