### ISSUE TITLE
Augmenter les polices de caractère dans les choix menu et la liste

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#5]
Augmenter les polices de caractère dans les choix menu et la liste 

![image001 1](https://cloud.githubusercontent.com/assets/12550052/22783208/a9aa9bd0-eec2-11e6-81c7-0e845b63fd8c.png)

A te lire,
bien cordialement.
Bernard BALLESTA
Mobile: 06 88 43 94 32

**Comment by ArianeFire** [comment]
La police de caractère dans le menu et la liste sont ok !

![menu](https://cloud.githubusercontent.com/assets/12550052/22840245/9d5d3e2a-efc4-11e6-8500-2c67ee9c5573.png)

En guise de teste : [http://163.172.174.219/LaraSpeedV2/public/film](url)

**Comment by ballesta** [comment]
Vu, 

 

Peux-tu agrandir encore un peu la taille des caractères.

 

De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : vendredi 10 février 2017 20:11
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Augmenter les polices de caractère dans les choix menu et la liste (#5)

 

La police de caractère dans le menu et la liste sont ok !

 <https://cloud.githubusercontent.com/assets/12550052/22840245/9d5d3e2a-efc4-11e6-8500-2c67ee9c5573.png> menu

En guise de teste : http://163.172.174.219/LaraSpeedV2/public/film

**Comment by ArianeFire** [comment]
C'est mieux comme ça ?  (Teste : [http://163.172.174.219/LaraSpeedV2/public/film](url) )

![size](https://cloud.githubusercontent.com/assets/12550052/22855917/be5fe094-f07f-11e6-80d1-9aaa44ba1b97.png)

**Comment by ballesta** [comment]
OUI, c’est bon !

 

De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : samedi 11 février 2017 18:30
À : LaraSpeed/LaraSpeed
Cc : Bernard BALLESTA; Comment
Objet : Re: [LaraSpeed/LaraSpeed] Augmenter les polices de caractère dans les choix menu et la liste (#5)

 

C'est mieux comme ça ? (Teste : http://163.172.174.219/LaraSpeedV2/public/film )

 <https://cloud.githubusercontent.com/assets/12550052/22855917/be5fe094-f07f-11e6-80d1-9aaa44ba1b97.png> size
