### ISSUE TITLE
Agrandir les boutons

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#6]
Agrandir les boutons et mettre un message d'aide sur survol genre "Add a new film"

![image001 2](https://cloud.githubusercontent.com/assets/12550052/22783267/f31ca40c-eec2-11e6-8b71-2b227283f81a.png)

**Comment by ArianeFire** [comment]
Le problème a été régler.
![btn_size](https://cloud.githubusercontent.com/assets/12550052/22826415/405050a8-ef8a-11e6-8bb3-1f7aba13ad04.png)

En guise de teste : [http://163.172.174.219/LaraSpeedV2/public/film](url)

**Comment by ballesta** [comment]
Vu,

 

Mais faudrait encore augment er la taille des boutons et les mettre dans des boutons avec un fond de  couleur :

 

Boutton view en vert

Bouton edit en orange

Bouton delete en rouge

 

 

               

e : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : vendredi 10 février 2017 13:14
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Agrandir les boutons (#6)

 

Le problème a été régler.
 <https://cloud.githubusercontent.com/assets/12550052/22826415/405050a8-ef8a-11e6-8bb3-1f7aba13ad04.png> btn_size

En guise de teste : http://163.172.174.219/LaraSpeedV2/public/film

**Comment by ArianeFire** [comment]
Voici un peu à quoi ça ressemble maintenant 

![buttons](https://cloud.githubusercontent.com/assets/12550052/22841751/9eaa934e-efca-11e6-8b4d-9ff93505aa15.png)

En guise de teste : [http://163.172.174.219/LaraSpeedV2/public/film](url)
