### ISSUE TITLE
Icones dans menu

### ISSUE THREAD

**Issue by ArianeFire** [LaraSpeed/LaraSpeed#9]
![image001 5](https://cloud.githubusercontent.com/assets/12550052/22783435/b034828a-eec3-11e6-9db2-67fe62fb5f48.png)

**Comment by ArianeFire** [comment]
Cette fonction a été ajouter, il est possible de spécifier l'icon pour chaque table à l'aide des icons de fontAwesome (fa fa-xxxx), comme sur l'image ci-dessous, en guise de teste : [http://163.172.174.219/LaraSpeedV2/public/category](url)

![icon](https://cloud.githubusercontent.com/assets/12550052/22998923/f699e064-f3d0-11e6-900c-56d626d902c7.png)

**Comment by ballesta** [comment]
De : Seydou Berthe [mailto:notifications@github.com] 
Envoyé : mercredi 15 février 2017 23:49
À : LaraSpeed/LaraSpeed
Cc : Subscribed
Objet : Re: [LaraSpeed/LaraSpeed] Icones dans menu (#9)

 

Cette fonction a été ajouter, il est possible de spécifier l'icon pour chaque table à l'aide des icons de fontAwesome (fa fa-xxxx), comme sur l'image ci-dessous, en guise de teste : http://163.172.174.219/LaraSpeedV2/public/category

 <https://cloud.githubusercontent.com/assets/12550052/22998923/f699e064-f3d0-11e6-900c-56d626d902c7.png> icon
